name: CI

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  backend:
    name: Backend tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install backend deps
        run: |
          cd apps/backend
          npm ci
      - name: Run backend tests
        run: |
          cd apps/backend
          npm run test

  frontend:
    name: Frontend tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install frontend deps & test
        run: |
          cd apps/frontend
          npm ci
          npm run test
